### ISSUE TITLE
Tweetledee errors

### ISSUE THREAD

**Issue by seunsodimu** [chrissimpkins/tweetledee#44]
Hi,
I followed the steps for installation on my server but I am getting this error 
"Call to undefined function mb_internal_encoding()" in tweetledee/tldlib/tmhUtilities.php on line 45.
Tweetledee Version: 0.4.1
PHP version: 5.4.26

**Comment by chrissimpkins** [comment]
It looks like the version of PHP on your server does not support this PHP built-in function.  `mb_internal_encoding()` is supported in all PHP5 versions.  Here is the documentation: 

http://php.net/manual/en/function.mb-internal-encoding.php 

I would check with your hosting provider to see if they are blocking this function for some reason.  If you have a local PHP install, you can test it there to confirm that this is the problem.

**Comment by seunsodimu** [comment]
Thanks!

**Comment by chrissimpkins** [comment]
my pleasure
