### ISSUE TITLE
enhance FAQ

### ISSUE THREAD

**Issue by malenki** [chrissimpkins/tweetledee#50]
First (since I haven't found another place to do so) thank you for this well documented and useful piece of software.

The "Issue": The [FAQ](https://chrissimpkins.github.io/tweetledee/support.html) for "I get the error "verify_credentials connection failure error"" could be enhanced by the nearly obvious
"You may have entered wrong credentials."
This happened to me having copied not only the twitter keys but also a preceding space. ;)

**Comment by chrissimpkins** [comment]
Sorry for the confusion.  Is it working for you now?

**Comment by malenki** [comment]
Chris Simpkins schrieb
am Fri, 13 Nov 2015 16:16:42 -0800:

> Sorry for the confusion.  Is it working for you now?

Yes, it is working.  
The space between "'" and the credentials is quite obvious as soon as
one looks at them. :)
